// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "prioritySource": string;
      "preLoadingPageNum": number;
      "autoRefresh": boolean;
      "notAutoRefreshItemTypes": string;
      "savePDFReferences": boolean;
      "saveAPIReferences": boolean;
      "notInLibraryOpacity": string;
      "showPopup": boolean;
      "popupDelay": number;
      "popupFadeMs": number;
      "popupRemoveDelay": number;
      "ctrlClickTranslate": boolean;
      "popupBackgroundColor": string;
      "popupTitleColor": string;
      "arXivInfoIndex": number;
      "DOIInfoIndex": number;
      "PMIDInfoIndex": number;
      "TitleInfoIndex": number;
      "clickLink": boolean;
      "clickLinkCmd": string;
      "hoverLink": boolean;
      "loadingRelated": boolean;
      "loadingCitations": boolean;
      "citationsPageSize": number;
      "graphEnable": boolean;
      "graphMaxNodes": number;
      "email": string;
      "s2ApiKey": string;
      "cacheTTLHours": number;
      "CNKI.username": string;
      "CNKI.password": string;
      "CNKI.token": string;
    };
  }
}
